[build]
rustflags = ["-C", "target-cpu=native"]
incremental = true
# jobs = 2 # number of parallel jobs, defaults to # of CPUs

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "target-cpu=native", "-C", "link-arg=-fuse-ld=mold"]

[alias]
xtask = "run --package xtask --"
